
export const NIETZSCHE_QUOTES = [
  "God is dead. God remains dead. And we have killed him.",
  "What does not kill me, makes me stronger.",
  "He who fights with monsters should look to it that he himself does not become a monster.",
  "And if you gaze long into an abyss, the abyss also gazes into you.",
  "You must have chaos within you to give birth to a dancing star.",
  "There are no facts, only interpretations.",
  "The man of knowledge must be able not only to love his enemies but also to hate his friends.",
  "I cannot believe in a God who wants to be praised all the time.",
  "It is not a lack of love, but a lack of friendship that makes unhappy marriages.",
  "That which is done out of love is always beyond good and evil.",
  "Amor Fati – ‘Love Your Fate’, which is in fact your life.",
  "The higher we soar the smaller we appear to those who cannot fly.",
  "Without music, life would be a mistake.",
  "To live is to suffer, to survive is to find some meaning in the suffering.",
  "In individuals, insanity is rare; but in groups, parties, nations and epochs, it is the rule.",
  "The true man wants two things: danger and play. For that reason he wants woman, as the most dangerous plaything.",
  "We should consider every day lost on which we have not danced at least once.",
  "Silence is worse; all truths that are kept silent become poisonous.",
  "No one can construct for you the bridge upon which precisely you must cross the stream of life, no one but you yourself alone.",
  "The snake which cannot cast its skin has to die. As well the minds which are prevented from changing their opinions; they cease to be mind.",
  "Every deep thinker is more afraid of being understood than of being misunderstood.",
  "I am not a man, I am dynamite.",
  "There is always some madness in love. But there is also always some reason in madness.",
  "One repays a teacher badly if one remains nothing but a pupil.",
  "Thoughts are the shadows of our feelings - always darker, emptier and simpler.",
  "Is man one of God's blunders? Or is God one of man's blunders?",
  "Art is the proper task of life.",
  "A thought comes when it will, not when I will.",
  "All things are subject to interpretation whichever interpretation prevails at a given time is a function of power and not truth.",
  "The lonely one offers his hand too quickly to whomever he encounters.",
  "I assess the power of a will by how much resistance, pain, torture it endures and knows how to turn to its advantage.",
  "The advantage of a bad memory is that one enjoys several times the same good things for the first time.",
  "When we are tired, we are attacked by ideas we conquered long ago.",
  "Ultimately, it is the desire, not the desired, that we love.",
  "It is hard enough to remember my opinions, without also remembering my reasons for them.",
  "Faith: not wanting to know what the truth is.",
  "In heaven, all the interesting people are missing.",
  "Man is the cruelest animal.",
  "The surest way to corrupt a youth is to instruct him to hold in higher esteem those who think alike than those who think differently.",
  "Blessed are the forgetful, for they get the better even of their blunders.",
  "A casual stroll through the lunatic asylum shows that faith does not prove anything.",
  "He who has a why to live can bear almost any how.",
  "Sometimes people don't want to hear the truth because they don't want their illusions destroyed.",
  "The doer alone learneth.",
  "One must pay dearly for immortality; one has to die several times while still alive.",
  "I love those who do not know how to live for today.",
  "Anyone who has declared someone else to be an idiot, a bad apple, is annoyed when it turns out in the end that he was not.",
  "There is more wisdom in your body than in your deepest philosophy.",
  "Morality is the herd-instinct in the individual.",
  "All truly great thoughts are conceived while walking.",
  "The best weapon against an enemy is another enemy.",
  "The future influences the present just as much as the past.",
  "I teach you the Overman. Man is something that shall be overcome.",
  "Man is a rope stretched between the animal and the Overman—a rope over an abyss.",
  "What is great in man is that he is a bridge and not a goal.",
  "You have your way. I have my way. As for the right way, the correct way, and the only way, it does not exist.",
  "Only where there are graves are there resurrections.",
  "Do not let yourself be deceived: Great minds are skeptical.",
  "Distrust all in whom the impulse to punish is powerful.",
  "He who climbs upon the highest mountains laughs at all tragedies, real or imaginary.",
  "Better to know nothing than to know many things by halves."
];
